apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/helloargo/ks-guestbook-demo-8080@sha256:af2e938f2f3a5b54b9ce4e14f1cd18732c9a1faca2201834fd5d0f8615867791
        name: guestbook-ui
        ports:
        - containerPort: 8080
