apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/it-eai--build/ks-guestbook-demo-8080:latest
        name: guestbook-ui
        env:
          - name: APACHE_RUN_DIR
            value: /tmp
          - name: APACHE_LOCK_DIR
            value: /tmp
          - name: APACHE_PID_FILE
            value: /tmp/apache2.pid
        ports:
        - containerPort: 8080
