apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/helloargo/ks-guestbook-demo-8080@sha256:cef32545619a4bc7dd01ff56635099ef582c339f9fe4e51b3ee05c6bcf3bc9d0
        name: guestbook-ui
        ports:
        - containerPort: 8080
